# Generated by Django 5.0.6 on 2024-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_customuser_city_customuser_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Enter Address', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Enter City', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='Enter Postal', max_length=20),
        ),
    ]
