# Generated by Django 5.0.6 on 2024-06-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_customuser_address_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
