# Generated by Django 5.0.6 on 2024-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bkash', 'Bkash'), ('Credit Card', 'Credit Card')], default='COD', max_length=20),
        ),
    ]
