# Generated by Django 5.0.6 on 2024-06-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_paid_order_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_placed',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='order_placed',
        ),
    ]
